name=AutoScripting
description=Starts target script in ghidra_scripts directory when Ghidra opens a program
author=Justin Faris
createdOn=10/09/2025
version=0.0.0
classes=autoscript.AutoStartPlugin